### ISSUE TITLE
cmd/rollappd/cmd: startInProcess leaks a database handle if an error occurs or if the app doesn't close the database

### ISSUE THREAD

**Issue by odeke-em** [dymensionxyz/rollapp#62]
**Describe the bug**
Noticed while auditing that this code https://github.com/dymensionxyz/rollapp/blob/25ff887ab3659169f7c4a0c5d91a57f0861380f8/cmd/rollappd/cmd/start.go#L205-L213 will leak the database handle on an error, leaving it open and on platforms like Windows that could cause problems if the database handle is retried but even crazier is the fact that a clever attacker can take advantage of an interesting UNIX (possibly POSIX) system flaw to hang onto a database handle and cause corruption later on per https://cyber.orijtech.com/scsec/unix-file-handle-perms

**Expected behavior**
Please use Go named returns to gracefully handle this closing
![image](https://github.com/dymensionxyz/rollapp/assets/4898263/4b02032e-2678-4cbd-a58f-a0ba85226756)

**Comment by omritoptix** [comment]
thank you for this @odeke-em! will make sure a team member goes over the details and fixes what's necessary.
